spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/masterschool?serverTimezone=GMT&nullCatalogMeansCurrent=true"
    username: EricLu
    password: lu168681816

  data:
    rest:
      base-path: /api
server:
  port: 8090
